// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppBDT.h"
#include <Rcpp.h>

using namespace Rcpp;

// toPOSIXct
Rcpp::DatetimeVector toPOSIXct(SEXP x);
RcppExport SEXP RcppBDT_toPOSIXct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    __result = Rcpp::wrap(toPOSIXct(x));
    return __result;
END_RCPP
}
