// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppBDT.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// toPOSIXct
Rcpp::NumericVector toPOSIXct(SEXP x, std::string tz);
RcppExport SEXP _RcppBDT_toPOSIXct(SEXP xSEXP, SEXP tzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type tz(tzSEXP);
    rcpp_result_gen = Rcpp::wrap(toPOSIXct(x, tz));
    return rcpp_result_gen;
END_RCPP
}
// charToPOSIXct
Rcpp::NumericVector charToPOSIXct(Rcpp::CharacterVector sv, std::string tz);
RcppExport SEXP _RcppBDT_charToPOSIXct(SEXP svSEXP, SEXP tzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< std::string >::type tz(tzSEXP);
    rcpp_result_gen = Rcpp::wrap(charToPOSIXct(sv, tz));
    return rcpp_result_gen;
END_RCPP
}
// cToPOSIXct
Rcpp::NumericVector cToPOSIXct(Rcpp::CharacterVector sv, std::string fmt, std::string tz);
RcppExport SEXP _RcppBDT_cToPOSIXct(SEXP svSEXP, SEXP fmtSEXP, SEXP tzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sv(svSEXP);
    Rcpp::traits::input_parameter< std::string >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< std::string >::type tz(tzSEXP);
    rcpp_result_gen = Rcpp::wrap(cToPOSIXct(sv, fmt, tz));
    return rcpp_result_gen;
END_RCPP
}
